parameters:
    # Default value for the Temporal collector endpoint
    env(OTEL_COLLECTOR_ENDPOINT): 'http://collector.addr:4317'
    env(OTEL_SERVICE_NAME): 'app-temporal-samples'
    # Default value for the Temporal server endpoint
    env(TEMPORAL_SERVER_ENDPOINT): 'http://temporal.addr:7233'

services:
    # default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services.
        autowire: true
        bind:
            $container: '@service_container'
            # Queue for the workflow and activity workers
            $temporalTaskQueue: '%env(TEMPORAL_TASK_QUEUE)%'

    Temporal\OpenTelemetry\Tracer:
        shared: false
        factory: ['App\Temporal\Factory\RuntimeFactory', 'tracer']
        arguments:
            $serviceName: '%env(OTEL_SERVICE_NAME)%'
            $collectorEndpoint: '%env(OTEL_COLLECTOR_ENDPOINT)%'

    Temporal\Client\WorkflowClientInterface:
        shared: false
        public: true # We need to have a facade for this service.
        factory: ['App\Temporal\Factory\RuntimeFactory', 'client']
        arguments:
            $serverAddress: '%env(TEMPORAL_SERVER_ENDPOINT)%'

    Temporal\WorkerFactory:
        factory: [null, 'create']

    Temporal\Worker\WorkerFactoryInterface: '@Temporal\WorkerFactory'

    Temporal\Worker\WorkerInterface:
        factory: ['App\Temporal\Factory\RuntimeFactory', 'worker']
        shared: false

    # Temporal classes
    App\Temporal\:
        shared: false
        resource: '../../src/Temporal/'

    App\Temporal\Runtime\RuntimeInterface: '@App\Temporal\Runtime\Runtime'

when@test:
    services:
        Temporal\WorkerFactory:
            factory: ['Temporal\Testing\WorkerFactory', 'create']
