parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services.
        autowire: true

    # Application activities
    App\Workflow\Service\Activity\:
        shared: false
        resource: '../../src/Workflow/Service/Activity/'
        tags: ['temporal.service.activity']
